version: '3'

services:
  playwright-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-vnc
    ports:
      - "5900:5900"  # VNC
      - "6080:6080"  # noVNC
      - "8888:8888"  # Jupyter
    volumes:
      - ./data:/app/data  # Mount a volume for data persistence
    restart: unless-stopped